apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-portal-ui
  labels:
    app: banking-portal-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-portal-ui
  template:
    metadata:
      labels:
        app: banking-portal-ui
    spec:
      containers:
      - name: banking-portal-ui
        image: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_PROJECT }}/banking-portal-ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: banking-portal-ui
spec:
  selector:
    app: banking-portal-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # No LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: banking-portal-ui
spec:
  to:
    kind: Service
    name: banking-portal-ui
  port:
    targetPort: 80
  tls:
    termination: edge
